// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5uUnVN_DbcxG7bdOpxw9MBORgtOKqzgg',
    appId: '1:138946141455:web:d73fd96b568d384c4a727a',
    messagingSenderId: '138946141455',
    projectId: 'hubinfobio',
    authDomain: 'hubinfobio.firebaseapp.com',
    storageBucket: 'hubinfobio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQo3b23reCFZEQMqUyOfW9ToP9jZtRTE8',
    appId: '1:138946141455:android:43fa544c19265af94a727a',
    messagingSenderId: '138946141455',
    projectId: 'hubinfobio',
    storageBucket: 'hubinfobio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsfjPCLNQ69fAwBGPnj6xyspazS6mwUrQ',
    appId: '1:138946141455:ios:066d2aeeb785a8c34a727a',
    messagingSenderId: '138946141455',
    projectId: 'hubinfobio',
    storageBucket: 'hubinfobio.firebasestorage.app',
    iosBundleId: 'com.example.hubInfobio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsfjPCLNQ69fAwBGPnj6xyspazS6mwUrQ',
    appId: '1:138946141455:ios:066d2aeeb785a8c34a727a',
    messagingSenderId: '138946141455',
    projectId: 'hubinfobio',
    storageBucket: 'hubinfobio.firebasestorage.app',
    iosBundleId: 'com.example.hubInfobio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5uUnVN_DbcxG7bdOpxw9MBORgtOKqzgg',
    appId: '1:138946141455:web:7565f1e943202df84a727a',
    messagingSenderId: '138946141455',
    projectId: 'hubinfobio',
    authDomain: 'hubinfobio.firebaseapp.com',
    storageBucket: 'hubinfobio.firebasestorage.app',
  );
}
